#Range: 1 ~ 4
itemsPerColumn = 4
#Range: 1 ~ 4
itemsPerRow = 4
diyData = true
showDevData = false
enchantsBlacklist = ["flimflam", "soulBound", "blindness", "curtail", "delicacy", "dullness", "echo", "encumberance", "fading", "fragility", "ignorance", "insomnia", "obedience", "radiance", "ruin", "silence", "sinking"]
hiddenTabs = []
dimensionsBlacklist = [-11]
disableLootManagerReloading = false

